import { demoProfile, activities, modules, blogPosts, welcomeMessage } from '@/lib/mock-data';
import { progressToNextLevel } from '@/lib/gamification';
import { StatCard } from '@/components/stat-card';
export default function DashboardPage() {
  const progress = progressToNextLevel(demoProfile.points);
  const nextModule = modules.find((module) => module.status === 'available');
  return (
    <main className="section"><div className="container dashboard-grid"><section className="grid"><div className="card panel accent-panel"><span className="pill">Hola, {demoProfile.full_name}</span><h1 style={{ marginBottom: 10 }}>{welcomeMessage.title}</h1><p style={{ lineHeight: 1.8, marginBottom: 0 }}>Esta demo muestra el tipo de experiencia que Bamboo puede generar dentro del holding: aprendizaje continuo, motivación visible y herramientas para que la gente crezca con más confianza, más criterio y más impacto en cualquier área de agencia.</p></div><div className="card panel"><h2 style={{ marginTop: 0 }}>Tu progreso en Bamboo</h2><div style={{ display: 'flex', gap: 18, alignItems: 'center', marginTop: 18 }}><div className="level-badge">{demoProfile.level}</div><div style={{ flex: 1 }}><strong style={{ display: 'block', fontSize: '1.1rem' }}>{demoProfile.level_name}</strong><div className="muted" style={{ marginBottom: 10 }}>{demoProfile.points} XP acumulados · Próximo nivel en {demoProfile.next_level_points} XP</div><div className="progress"><span style={{ width: `${progress.percent}%` }} /></div></div></div></div><div className="grid three-up"><StatCard label="Racha" value={`${demoProfile.streak_days} días`} hint="Mantén actividad mensual" /><StatCard label="Módulos completados" value="2/4" hint="Ruta inicial Bamboo" /><StatCard label="Artículos publicados" value="1" hint="Escribir también acelera tu crecimiento" /></div><div className="card panel"><h2 style={{ marginTop: 0 }}>Actividades del mes</h2><ul className="list-clean">{activities.map((activity) => <li key={activity.id} className="item-row" style={{ alignItems: 'flex-start' }}><div><strong>{activity.title}</strong><div className="muted">{activity.date_label} · {activity.category}</div><div className="muted" style={{ marginTop: 6 }}>{activity.description}</div></div><span className="pill">+{activity.xp_reward} XP</span></li>)}</ul></div></section><section className="grid"><div className="card panel"><h2 style={{ marginTop: 0 }}>Siguiente módulo recomendado</h2><strong>{nextModule?.title}</strong><p className="muted" style={{ lineHeight: 1.7 }}>{nextModule?.description}</p><p style={{ lineHeight: 1.7 }}>{nextModule?.takeaway}</p><button className="btn btn-primary">Continuar</button></div><div className="card panel"><h2 style={{ marginTop: 0 }}>Tu actividad editorial</h2><ul className="list-clean">{blogPosts.map((post) => <li key={post.id} className="item-row" style={{ alignItems: 'flex-start' }}><div><strong>{post.title}</strong><div className="muted">{post.status === 'published' ? 'Publicado' : 'Borrador'} · {post.tag}</div><div className="muted" style={{ marginTop: 6 }}>{post.summary}</div></div><span className="pill">+{post.xp_reward} XP</span></li>)}</ul></div></section></div></main>
  );
}
